bot de python.pybot de python.pyPublicar Tasa BCV
#hora de la publicación, desfazado 12.5 horas porque la hora de la publicación bcv no es consistente.
en:
  cronograma:
    - cron: '15 9 * * 1-5'
  flujo de trabajo_despacho: 

empleo:
  construir:
    run-on: ubuntu-último
    pasos:
      - nombre: Checkout del código
        usos: acciones/checkout@v4

      - nombre: Configurar Python
        usos: acciones/setup-python@v5
        con:
          versión python: '3.9'

      - nombre: Instalar libres
        run: |
          solicitudes de instalación de pip beautifulsoup4 urllib3

      - nombre: Guión ejecutivo
      #envio a servidores de discordia
        env:
          DISCORD_WEBHOOK: ${{ secretos.DISCORD_WEBHOOK }}
        run: bot de python.py
