name: Publicar Tasa BCV

# Hora de la publicación, desfasado 12.5 horas porque la hora de la publicación bcv no es consistente.
on:
  schedule:
    - cron: '15 9 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: |
          pip install requests beautifulsoup4 urllib3

      - name: Ejecutar script
        # Envió a servidores de discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python bot.py
